# Generated by Django 4.2 on 2023-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vaccinations',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='pet',
            field=models.ManyToManyField(to='main_app.pet'),
        ),
    ]
