# Generated by Django 4.2 on 2023-04-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_pet_vaccinations_vaccination_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='pet',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.pet'),
            preserve_default=False,
        ),
    ]
