# Generated by Django 4.2 on 2023-04-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_vaccination_pet_vaccination_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grooming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Grooming Date')),
                ('duration', models.IntegerField()),
                ('nail_trim', models.BooleanField()),
                ('hair_trim', models.BooleanField()),
                ('teeth_brush', models.BooleanField()),
                ('bath', models.BooleanField()),
                ('shampoo', models.BooleanField()),
                ('conditioner', models.BooleanField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pet')),
            ],
        ),
    ]
