# Generated by Django 4.2 on 2023-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_visit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='vaccines',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='visit',
            field=models.ManyToManyField(to='main_app.visit'),
        ),
    ]
