# Generated by Django 4.2 on 2023-05-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_visit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='vaccines',
            field=models.ManyToManyField(null=True, to='main_app.vaccination'),
        ),
    ]
