# Generated by Django 4.2 on 2023-05-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_vaccination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(null=True, verbose_name='Vaccination Date'),
        ),
    ]
